### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by TbtBI** [pinterf/AddGrainC#4]
```
w = 380
h = 180

yv12 = blankclip(pixel_type="yv12" ,color=$808080,width=w,height=h,length=10).loop(1000000)
yuy2 = blankclip(pixel_type="yuy2" ,color=$808080,width=w,height=h,length=10).loop(1000000)
rgb =  blankclip(pixel_type="rgb24",color=$808080,width=w,height=h,length=10).loop(1000000)
rgba = blankclip(pixel_type="rgb32",color=$808080,width=w,height=h,length=10).loop(1000000)

opt =false
for (i = 0, 109)
{
stackhorizontal ( \
	stackvertical(yv12.addgrainc(200,200, sse2=opt).ConvertToRGB32(), \
		yuy2.addgrainc(200,200,seed=12, sse2=opt).ConvertToRGB32(), \
		yuy2.addgrainc(200,200, sse2=opt).ConvertToRGB32(), \
		rgb.addgrainc(200,200, sse2=opt).ConvertToRGB32(), \
		rgba.addgrainc(200,200, sse2=opt).ConvertToRGB32() \
	), stackvertical(yv12.addgrainc(200,200,constant=true, sse2=opt).ConvertToRGB32(), \
		yuy2.addgrainc(200,200,seed=12,constant=true, sse2=opt).ConvertToRGB32(), \
		yuy2.addgrainc(200,200,constant=true, sse2=opt).ConvertToRGB32(), \
		rgb.addgrainc(200,200,constant=true, sse2=opt).ConvertToRGB32(), \
		rgba.addgrainc(200,200,constant=true, sse2=opt).ConvertToRGB32() \
	) \
)
}
```
Hi. Using the above script gives output like this - https://images2.imgbox.com/31/e2/uIhvPfHi_o.png 
Note the purple line. This line can be sometimes green, very bright, in different location. Sometimes there are two lines, sometimes the output looks ok.
`opt=false/true` seems change nothing.

Other issue - the above script rarely crashes avspmod with error something like "cannot read memory location". This crash happens randomly and I didn't find a way to reproduce it.

**Comment by pinterf** [comment]
1.) using variable name 'rgba' made me problems, one of my zillion plugins defines 'rgba' as a variable or function or whatever and made it NULL between two addgrainc calls (plugin autoload?) and a second call to rgba.addgrainc always reported "invalid parameters for function addgrainc"
Now I renamed it in the test script to rgbb to keep my nerves calm :) and finally I was able to start testing
2.) Purple line appears for YUY2 for me. Must be a real bug. 

Until then could you test if your avspmod crash still occurs if you replace YUY2 with another format e.g. YV16? (I suspect false memory access due to a wrong size calculation)
(depends on how you define 'rarely', if 1 of 1000 then forget my ask)

**Comment by TbtBI** [comment]
Replacing YUY2 with YV16 also causes crash - https://images2.imgbox.com/16/a8/AWu3dGVo_o.png

**Comment by pinterf** [comment]
Thanks, that at least helps where not to search bugs.

**Comment by pinterf** [comment]
I'd need more info because I am unable to reproduce the crash. I suppose you are using 64 bit builds.
Avsmod version
AviSynth version
AddgrainC build (xp, cland, msvc was in the 1.8.3 pack)
Windows XP or not, 
CPU type
When does the crash occur: upon script load, reload, continous playing, jumping between non-consecutive frames, etc..?

**Comment by TbtBI** [comment]
> Replacing YUY2 with YV16 also causes crash - https://images2.imgbox.com/16/a8/AWu3dGVo_o.png

That's not true. The script test from the first comment is a bit modified version of addgrain.avsi. When I tested with YV16, addgrain.avsi was still in my autoloaded folder. Removing addgrain.avsi and using YV16 instead of YUY2 I cannot get crash. I'm sorry about the wrong info I shared in my previous comment.

Btw the crash with YUY2 occurs upon script load. r3620, x64+, Windows 10 is used. Usually I have to open and close AvsPmod 10-15 times to get the crash.

**Comment by pinterf** [comment]
Thanks for the clarification. I'm gonna implement real YUY2 support simply by autoconverting it internally to YV16. This is needed because uvar parameter must work properly.

**Comment by pinterf** [comment]
Pls. check release 1.8.4

**Comment by TbtBI** [comment]
It works perfectly.
Thanks.
